### ISSUE TITLE
Tests fail on PkgEval now

### ISSUE THREAD

**Issue by IainNZ** [queryverse/ExcelReaders.jl#15]
http://pkg.julialang.org/logs/ExcelReaders_0.3.log

Is something not right with the new Conda stuff?

**Comment by davidanthoff** [comment]
I think two different causes for julia 0.3 and 0.4.

The last ExcelReaders version to support julia 0.3 was ExcelReaders 0.3.0, and the whole Conda support was only added in ExcelReaders 0.4.0, which is julia 0.4 only. I've put it on the todo list davidanthoff/ExcelReaders.jl#16, but not sure when I will have time for that.

For julia 0.4, the error is probably this: if there is a system python installed, PyCall will use that. I believe the Conda stuff ONLY kicks in if there is no python installed at all. But when a system python is present, one has to manually install any package that one needs via pip or something like it. Not sure what to do about this, maybe just revert to installing xlrd via pip for now on the PkgEval front...

CCing @dhoegh, who added the Conda support to ExcelReaders, and @Luthaf, who maintains Conda.

**Comment by dhoegh** [comment]
> For julia 0.4, the error is probably this: if there is a system python installed, PyCall will use that. I believe the Conda stuff ONLY kicks in if there is no python installed at all. But when a system python is present, one has to manually install any package that one needs via pip or something like it. Not sure what to do about this, maybe just revert to installing xlrd via pip for now on the PkgEval front...

Conda should kick in and be used if a `PYTHON=""` is set as environment variable. @IainNZ, is the enviroment variable set here: https://github.com/IainNZ/PackageEvaluator.jl/blob/753dc644f209b38b2822531d52738609b6973192/scripts/setup.sh#L83 avaible at PyCall build time?

I could probably look into backporting the Conda support for 0.3 in the next couple of days.

**Comment by IainNZ** [comment]
It should be available, yes.

**Comment by dhoegh** [comment]
> It should be available, yes.

Then I am at a loss. Because if the `PYTHON=""` then PyCall should detect it at line: https://github.com/stevengj/PyCall.jl/blob/44fe6817a879c466b19f8569bede6b72380e894e/deps/build.jl#L126. Setting Travis up to use Conda is as simple as setting the `PYTHON` environment variable, see https://github.com/jverzani/SymPy.jl/blob/fe7353d110c0c89e2ef6346789c2b000cf0d4726/.travis.yml#L10. The value of the `PYTHON` environment variable is irelavent as long as it's not `PYTHON="python"`.

**Comment by IainNZ** [comment]
So you can see in the log:

```
>>> 'Pkg.add("ExcelReaders")' log
INFO: Cloning cache of ExcelReaders from git://github.com/davidanthoff/ExcelReaders.jl.git
INFO: Installing ArrayViews v0.6.4
INFO: Installing Conda v0.1.8
INFO: Installing DataArrays v0.2.20
INFO: Installing DataFrames v0.6.10
INFO: Installing Dates v0.4.4
INFO: Installing ExcelReaders v0.4.0
INFO: Installing GZip v0.2.18
INFO: Installing PyCall v1.2.0
INFO: Installing Reexport v0.0.3
INFO: Installing SortingAlgorithms v0.0.6
INFO: Installing StatsBase v0.7.4
INFO: Installing StatsFuns v0.2.0
INFO: Building PyCall
INFO: PyCall is using /usr/bin/python (Python 2.7.6) at /usr/bin/python, libpython = libpython2.7
INFO: Package database updated
INFO: METADATA is out-of-date — you may not have the latest version of ExcelReaders
INFO: Use `Pkg.update()` to get the latest versions of your packages
```

So its using system Python there. Is it possible that something else is changing the environment variable?

**Comment by IainNZ** [comment]
Shouldn't
`export PYTHON = ""`
be 
`export PYTHON=""`
??

**Comment by dhoegh** [comment]
I think it should. Could that be it, if so then my Python habit's struck me.

**Comment by IainNZ** [comment]
I mean, the version thats in there isn't valid Bash, so, hopefully that'll do it. I'll reopen if it isn't fixed on next run.
