### ISSUE TITLE
Why not use AbstractArray{Nullable{T}, N} or NullableArray{T, N}?

### ISSUE THREAD

**Issue by lewisl** [queryverse/ExcelReaders.jl#19]
OK, it's one thing not to do so when reading in as DataArray.

But, the point of DataFrames is they already provide support for NA.  But, it appears that when you scan though a column containing any NA even if all other values are of the same type you create a DataArray of that type for the column.  So, that just breaks NA handling.

At the risk of increasing memory usage (quite real risk) why not convert the raw array you read in from the Excel sheet to DataFrames and let DataFrames figure out the types and do it's default NA handling?  Maybe I don't understand so just a sort of brute force thought.

Given this limitation I'll just export the Excel data I was using (some state dept of education data) as csv and use the DataFrames package csv reader, which _might_ handle the NAs.  I'll report back if this works.

Thanks--I realize this is new work and relying on python xlrd, so no automatic handling for NAs there.

**Comment by lewisl** [comment]
Using DataFrames readtable on a csv file works as expected.

**Comment by davidanthoff** [comment]
I don't understand this at all. Can you try to be more precise what you a) think the problem is and b) what you suggest as a solution? In particular, it would be good to get an example of what kind of data you are trying to read, what you currently get, and what you would like to get instead.

A few random comments.

DataFrames currently has no support for anything related to `Nullable` or `NullableArray`. I don't understand how using those two would help with `DataFrames` interop.

> But, the point of DataFrames is they already provide support for NA. But, it appears that when you scan though a column containing any NA even if all other values are of the same type you create a DataArray of that type for the column. So, that just breaks NA handling.

Yes, DataFrames provides NA support by using DataArrays. So passing in a DataArray when there is a NA present is the way to use this. I don't understand what you think is currently broken with respect to NA handling.

> At the risk of increasing memory usage (quite real risk) why not convert the raw array you read in from the Excel sheet to DataFrames and let DataFrames figure out the types and do it's default NA handling? Maybe I don't understand so just a sort of brute force thought.

I don't understand. As what type would you hand the data to DataFrames? DataFrames doesn't convert stuff if you create it in memory, as far as I know, so unless you pass in a DataFrame, I don't think you would get any NA handling.

**Comment by lewisl** [comment]
The data itself is simple:  various statistics collected about school districts in the state of Washington.  There are about 310 districts.  A typical sheet has perhaps 20-30 measures per district.  Measures are usually int or float.  Descriptors are text or int (which I convert to text).  So, the data is tiny; about what you'd expect for social science data.

What happens:  columns that contain rows with NA data, encoded as "n/a" rather than "" or "NA", end up as type Any, which is pretty much useless for analysis.  Using readable() from DataFrames will encode the "n/a" as zero, which preserves the numeric type but is wrong, of course.  readable() has the nastrings = ["", "NA", "n/a", <anything you want...>], which encodes the listed string values as NA.  This then preserves the column type to match all of the other non-NA entries (assuming they are the same).

So, I was wrong about the cause:  the dataframe container provides the special handling of NA's for many (not all) statistical functions with suitable methods.  Has nothing to do with the array type used for the column.  Nullable is not needed.

It would seem that the solution for readxl with the DataFrame type argument would be to offer a method with a splat for arguments to be passed to readtable. Excel readers instead reads the data using xlrd, then walks through row values by column to decide what type to use.  After reading in the raw data, can you just convert to DataFrame and let it do the magic?

At this point, it's just more reliable to export xls to csv (Excel naturally manages to botch even this by leaving trailing commas on every row), munge the csv files in Sublime Text, and then load the csv's directly into data frames.

If I really had a lot of this I'd do the munging programmatically in Julia, but most of the work is figuring out what the dept of education did.  Once that is clear (?) then the munging is easy.

Just thought that excel readers could be more data frames aware and let it do some of the auto-munging it has (eltypes is another example).

**Comment by lewisl** [comment]
Here is another example of something that happens:

LoadError: DataArrays.NAException("Cannot convert DataArray with NA's to desired type")
while loading In[5], in expression starting on line 1

This is caused by some rows that contain columns (measures) with some "n/a" values and a bunch of blanks.

It just seems that read excel should read whatever it can and then let me clean it up.  Failing to read at all seems like the wrong outcome.

**Comment by davidanthoff** [comment]
> It would seem that the solution for readxl with the DataFrame type argument would be to offer a method with a splat for arguments to be passed to readtable. Excel readers instead reads the data using xlrd, then walks through row values by column to decide what type to use. After reading in the raw data, can you just convert to DataFrame and let it do the magic?

`readtable` reads text files, so using that is not an option here. But it seems to me that all you are asking for is to add support for a `nastrings` argument to the various functions in ExcelReaders. That would be entirely enough to solve your issues, right?

**Comment by davidanthoff** [comment]
> Here is another example of something that happens:
> 
> LoadError: DataArrays.NAException("Cannot convert DataArray with NA's to desired type")
> while loading In[5], in expression starting on line 1
> 
> This is caused by some rows that contain columns (measures) with some "n/a" values and a bunch of blanks.
> 
> It just seems that read excel should read whatever it can and then let me clean it up. Failing to read at all seems like the wrong outcome.

Can you open another issue for this? It seems a separate request/problem than the original issue here. Better to track them in separate issues. Also, can you always post the exact method you called, what arguments etc? And if possible even a small reproduction Excel file? That would make finding the root issue much easier.
