### ISSUE TITLE
Read named references

### ISSUE THREAD

**Issue by fbanez** [queryverse/ExcelReaders.jl#21]
Hi!
I was trying to read an specific range of an excel file (defined in Excel), like this:
dfData = readxl(DataFrame, file0, "Control!Investments", header=false)

But I think it can't be done right now. Is it possible? 
If not, I think it is useful to incorporate this option.

Thanks!

**Comment by davidanthoff** [comment]
Yes, this is a good suggestion. The underlying xlrd package supports this, so it shouldn't be too difficult to add this. I don't have the time to do this anytime soon, but PRs would be most welcome.

I've slightly renamed the issue to use the terminology of xlrd.

**Comment by fbanez** [comment]
OK, perfect!
I would like to help, but I am still learning how to use Julia that I do not know how...

**Comment by davidanthoff** [comment]
A first stab is now on ``master``. Still needs tests and documentation.
