### ISSUE TITLE
use pyimport_conda

### ISSUE THREAD

**Issue by stevengj** [queryverse/ExcelReaders.jl#22]
As of PyCall 1.5, you can now just do `pyimport_conda("xlrd", "xlrd")` to auto-install xlrd via Conda (if PyCall is using Conda) or print an informative error message, rather than duplicating that logic here.   This will also let you remove the explicit Conda dependency.

**Comment by davidanthoff** [comment]
@stevengj Thanks, this is really useful for downstream packages!
