### ISSUE TITLE
Fail if first cell empty

### ISSUE THREAD

**Issue by JonWel** [queryverse/ExcelReaders.jl#28]
When loading to a DataFrame, if the first cell of the first column is empty (remaining of the column has content), it fails with

``` Julia
LoadError: type Void has no field captures
 in convert_ref_to_sheet_row_col at C:\User\.julia\v0.4\ExcelReaders\src\ExcelReaders.jl:177
 in readxl at C:\User\.julia\v0.4\ExcelReaders\src\ExcelReaders.jl:246
 in include_string at loading.jl:282
 in include_string at C:\User\.julia\v0.4\CodeTools\src\eval.jl:32
 in anonymous at C:\User\.julia\v0.4\Atom\src\eval.jl:84
 in withpath at C:\User\.julia\v0.4\Requires\src\require.jl:37
 in withpath at C:\User\.julia\v0.4\Atom\src\eval.jl:53
 [inlined code] from C:\User\.julia\v0.4\Atom\src\eval.jl:83
 in anonymous at task.jl:58
```

Wouldn't it better to fill it with something like `A` (as DataFrame needs a name for the column)?

To reproduce:

``` Julia
using ExcelReaders
using DataFrames

f = openxl("Filename.xlsx")
df = readxl(DataFrame, f, "Sheet1")
```

**Comment by davidanthoff** [comment]
`readxl` only works with fully specified Excel ranges, i.e. `Sheet1!A1:C4`. You should use `readxlsheet` if you want the package to automatically find the data on the sheet. I've added a more helpful error message to the package (but won't tag a new version until there are more new features accumulated).

**Comment by JonWel** [comment]
Right, I did not saw the command name was different for the case when specifying the sheet without the range.
I sometimes tend to read a bit too globally (ie I just recognise part of the words instead of really reading all the letters).

Thank you for the precision, and good idea to have improved the error message.
In deed, no need for a new version just for that.
