### ISSUE TITLE
makes things simpler?

### ISSUE THREAD

**Issue by bbrunaud** [queryverse/ExcelReaders.jl#30]
Hello. So far I've enjoyed the use of ExcelReaders. I think there are a few tweaks that could make it simpler and easier.

1) Is there a reason to have a separated readxl and readxlsheet functions?. Could the readxl funtion detect when you are not supplying a range and assume you want the whole sheet?. Maybe just with the number of arguments?. 

2) Can the module require DataFrames and give a DataFrame as output by default?. If a DataArray is more convenient fore a certain application can this be selected with a keyword argument?.

thanks

Braulio

**Comment by davidanthoff** [comment]
`readxl` and `readxlsheet` take different optional arguments, and I wanted to make sure that e.g. an editor that can show method signatures would show the correct arguments.

I think in terms of return type I'm going to wait and see a bit. There are some massive changes coming to `DataFrame`... I also have a whole new way of representing tables in [Query.jl](https://github.com/davidanthoff/Query.jl) that is a lot more flexible, and I might integrate into that system. But I think for now it is best to first wait and see how this whole data handling ecosystem shakeout that is happening right now will end.

**Comment by davidanthoff** [comment]
The way to read this into a DataFrame now is [ExcelFiles.jl](https://github.com/queryverse/ExcelFiles.jl) (which uses ExcelReaders under the hood). In terms of API, I'm going to keep things the way they are, breaking changes are just too disruptive.
