### ISSUE TITLE
Reading excel: ArgumentError: ref of NULL PyObject

### ISSUE THREAD

**Issue by jerryhxg** [queryverse/ExcelReaders.jl#31]
i've tried to read xlsx file bying using readxl, by returning the NULL error. the Excel Readers tests passed though, with pycall functioning well. Any thing else i can try to fix ?

**Comment by davidanthoff** [comment]
Can you give more information to reproduce this? Ideally post the exact code that you are using to fall ``readxl`` and also paste the exact error message.

**Comment by jerryhxg** [comment]
Dear David.  

thank you very much. 

after deleting a column of names for data, it can import and shows no error now. so i guess the problem shall be with the structure of naming.  i will figure out that column later.  thanks a lot.
