### ISSUE TITLE
Is there reason to prevent constructing DataFrame with empty column name? 

### ISSUE THREAD

**Issue by YongHee-Kim** [queryverse/ExcelReaders.jl#34]
I found that if top row has any empty cell, I cannot use `readxlsheet(DataFrame......`

This code below would allow constructing DataFrame with an empty column name, But I don't know if this is an intentional restriction or not. 14ca83cca389703a74c675be0a4360b3101ff361
``` julia 
        if header
            headervec = data[1, :]
            NAcol = Bool.(isna(headervec))
            headervec[NAcol] = DataFrames.gennames(countnz(NAcol))

            colnames = convert(Array{Symbol},vec(headervec))
        else
            colnames = DataFrames.gennames(ncol)
        end
 ```

**Comment by davidanthoff** [comment]
I think that would be a good change, do you want to open a PR?

**Comment by YongHee-Kim** [comment]
got it😄 I will open a PR
