### ISSUE TITLE
Make things work with julia 0.4

### ISSUE THREAD

**Issue by davidanthoff** [queryverse/ExcelReaders.jl#4]

**Comment by davidanthoff** [comment]
@mbauman mentioned that the changes in JuliaLang/julia#10525 break ExcelReaders (he mentioned that [here](https://github.com/JuliaStats/DataArrays.jl/pull/152#issuecomment-111148060)).

Once we look at 0.4 compatibility we should address that.

@mbauman, just to clarify, are you sure that commit surfaced a new problem in ExcelReaders? ExcelReaders at no point worked with 0.4, so maybe you just saw a test failure that was there before already? I will look at 0.4 compatibility once there is a feature freeze for 0.4.

**Comment by mbauman** [comment]
Ah, no, I'm not. I made a quick assessment based on the day it failed and the error message backtrace. But looking through the code now I don't see any reason why that would have caused it.

**Comment by mbauman** [comment]
Ah, yeah, looks like you got hit by a cascading failure from https://github.com/JuliaStats/DataArrays.jl/pull/152.  The backtraces from DataArrays are particularly bad due to the compat macros.  Sorry for the false alarm!

**Comment by davidanthoff** [comment]
Thanks!
