### ISSUE TITLE
ExcelReaders.jl is holding DataFrames and DataArray update?

### ISSUE THREAD

**Issue by YongHee-Kim** [queryverse/ExcelReaders.jl#46]
![image](https://user-images.githubusercontent.com/7087745/33916430-24fb70f0-dfec-11e7-90c3-9d4c8bbe7707.png)

Julia seems to think that ExcelReaders is holding DataFrame update. 
But there is no upper bound in [require](https://github.com/davidanthoff/ExcelReaders.jl/blob/master/REQUIRE) file.

**Comment by davidanthoff** [comment]
See #45 for the plan to address this. The upper bound is in METADATA.jl. I'm pretty busy with other stuff right now, so not entirely sure when I'll be able to do this.
