### ISSUE TITLE
Empty cells in xls Julia showing as NA. Julia does not recognize this sign.

### ISSUE THREAD

**Issue by programistawpf** [queryverse/ExcelReaders.jl#51]
Empty cells in xls Julia showing as NA. Julia does not recognize this sign. 
`julia> a=readxlsheet("dane/dane.xlsx","Arkusz1")
3×3 DataArrays.DataArray{Any,2}:
 0.946871  0.753045  0.789162
 0.867544   NA       0.940965
 0.381519  0.456175  0.0888175

julia> sum(a)
NA
julia> findin(a,NA)
ERROR: UndefVarError: NA not defined
julia> findin(a,"NA")
0-element Array{Int64,1}
julia> findin(a,'NA')
ERROR: syntax: invalid character literal
julia> typeof(a[2,2])
DataArrays.NAtype
julia> (a[2,2])
NA`
![xlsx_data](https://user-images.githubusercontent.com/5564741/38538530-94be3134-3c94-11e8-8efa-1f335fa0e5b4.png)

IS posible to change it fo native for Julia NaN ? Paul

**Comment by programistawpf** [comment]
How to import empty cels like zeros ? 
julia> using ExcelReaders

julia> readxlsheet("dane.xlsx","Arkusz1")
3×3 Array{Any,2}:
 1.0    #NA   #NA
  #NA  0.0    #NA
  #NA   #NA  3.0

**Comment by davidanthoff** [comment]
Sorry for a slow response! If you load the [DataValues.jl](https://github.com/queryverse/DataValues.jl) package, you have access to the ``NA`` value, and then you can find indices etc:
````julia
using DataValues

findall(i->i==NA,a)
````
should then just work.

**Comment by programistawpf** [comment]
It is only caretsian list, ho to replace #NA for 0  ?
