### ISSUE TITLE
Error in kwfunc

### ISSUE THREAD

**Issue by lucasfreitas1988** [queryverse/ExcelReaders.jl#52]
Hello! I need Help!

My code - data = readxl(DataFrame, "A.xlsx", "Sheet!A1:X1834", header=true) - results in 

function readxl does not accept keyword arguments
kwfunc(::Any) at boot.jl:237
include_string(::String, ::String) at loading.jl:522
include_string(::String, ::String, ::Int64) at eval.jl:30
include_string(::Module, ::String, ::String, ::Int64, ::Vararg{Int64,N} where N) at eval.jl:34
(::Atom.##102#107{String,Int64,String})() at eval.jl:82
withpath(::Atom.##102#107{String,Int64,String}, ::String) at utils.jl:30
withpath(::Function, ::String) at eval.jl:38
hideprompt(::Atom.##101#106{String,Int64,String}) at repl.jl:67
macro expansion at eval.jl:80 [inlined]
(::Atom.##100#105{Dict{String,Any}})() at task.jl:80

Before, this code it resulted in PyError (IOError, 2, not such file or directory). I think maybe be one error in PyCall, butt I am not right. When i closed Atom and reopen, the error changed for function readxl... keyword arguments. I am confused!

What is this?

Thank you so much!

Best

**Comment by davidanthoff** [comment]
All the functionality related to `DataFrame` (or any tabular structure) was moved to https://github.com/davidanthoff/ExcelFiles.jl, so you'll need to use that package.
