### ISSUE TITLE
xlrd not automatically installed

### ISSUE THREAD

**Issue by cmcaine** [queryverse/ExcelReaders.jl#67]
> The package uses the Python xlrd library. If either Python or the xlrd package are not installed on your system, the package will use the conda.jl package to install all necessary dependencies automatically.

I had to set `ENV["PYTHON"]=""`, rebuild PyCall, restart Julia and then import ExcelReaders again to get PyCall to install xlrd.

I don't know if this is intended behaviour, but it certainly adds caveats to the above statement from the Readme (i.e. "package will use the conda.jl package to install all necessary dependencies automatically if you already have a Julia conda environment installed. If you do not...")

**Comment by davidanthoff** [comment]
Good point! I think this might be mainly an issue on Linux systems, doesn't PyCall install its own version of Python by default on Win and Mac? Not sure. In any case, any PR with language for the README that clarifies this would be most welcome, we just need to make sure it applies to all platforms equally.

**Comment by cmcaine** [comment]
Just checked the docs and tested on Windows myself. I'll open a PR that explains that on other systems you need to install your own xlrd or follow the instructions on PyCall.jl

**Comment by davidanthoff** [comment]
My best guess is that the story on Mac is similar to Windows, but not sure...
