### ISSUE TITLE
Feature request: read entire sheet into dataframe

### ISSUE THREAD

**Issue by amellnik** [queryverse/ExcelReaders.jl#9]
As far as I can tell, it's possible to read an entire sheet using readxlsheet or read to a dataframe using readxl(DataFrame ...).  Could we also have an option that lets us read an entire sheet into a dataframe (or is this possible and I'm just missing it?)

**Comment by davidanthoff** [comment]
Not implemented yet, but I totally agree this should be added.

**Comment by amellnik** [comment]
I'm starting to go through the code, I'll also try and see if I can get it working.
