### ISSUE TITLE
xlrd 2.0.1 issues

### ISSUE THREAD

**Issue by PaulSoderlind** [queryverse/ExcelReaders.jl#98]
the xlrd documentation now (as of Dec 2020) says
```This library will no longer read anything other than .xls files. ```

I gave it a try, and ExcelReaders+xlrd 2.0.1 indeed fail on an xlsx file, so I had to revert to xlrd 1.2.0.

May I ask what the plans for ExcelReaders.jl are?

**Comment by davidanthoff** [comment]
Yeah, this has been a big problem... I'm now making this package officially old-Excel files only, i.e. I'm following the xlrd lead here. For modern Excel files XLSX.jl is the way to go, I think.

I'll make ExcelFiles.jl support both types going forward.
